--
-- Display had problems publishing providers. 
--

select distinct PROVIDERS.*
from CALLBACKS,
     AUDIT_API_REQUEST,
     PROVIDERS
where CALLBACKS.LOGON_USER = AUDIT_API_REQUEST.LOGON_USER
and PROVIDERS.ID = CALLBACKS.LOGON_BROADCAST_PROVIDER
and AUDIT_API_REQUEST.HTTP_STATUS_CODE not in(0,200)
and AUDIT_API_REQUEST.USER_EMAIL is not null;
