#This is a sample batch script to run the customer report

println ********************************************************************
println Pring Paul tool instruction
println ********************************************************************
gscript -help

println ********************************************************************
println List the available groovy script to run
println ********************************************************************
gscript -l

println ********************************************************************
println Run the customer report
println ********************************************************************
set --host=http://apiv1.farreach.es
gscript CustomerProblemReport userEmail=mharmuth@fortunatefamilies.com publicUri=http://fortunatefamilies.com

exit
