#This is a sample batch script for the amplafi flow client shell

#Available commands:

#EXIT      Exit this shell.
#HELP      Print this help instructions.
#ENV       Print the shell environment such: host, port, api version, api key...
#SET       Set the shell environment such: host, port, api version, api key...
#PRINTLN   Print a message
#LIST      List the available flow for the selected api version
#DESC      Show the description of a flow
#FLOW      Run a flow
#TUTORIAL  Run the tutorial flow.


println ********************************************************************
println Help Instruction
println ********************************************************************
help

println ********************************************************************
println Set Api Version
println ********************************************************************
set --apiv=apiv1

println ********************************************************************
println EligibleExternalServiceInstancesFlow
println ********************************************************************
desc --name=EligibleExternalServiceInstancesFlow
flow --name=EligibleExternalServiceInstancesFlow

println ********************************************************************
println AvailableCategoriesFlow
println ********************************************************************
flow --name=AvailableCategoriesFlow

println ********************************************************************
println MessageEndPointListFlow 
println ********************************************************************
flow --name=MessageEndPointListFlow --messageEndPointCompleteList=true

exit
